nodeLinker: node-modules

npmScopes:
  statik-space:
    npmAlwaysAuth: true
    npmAuthToken: "${STATIK_REGISTRY_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com/"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
