---
default-src:
  - "'self'"
style-src:
  - "'self'"
  - "'unsafe-inline'"
script-src:
  - "'self'"
  - "'unsafe-inline'"
font-src:
  - "'self'"
img-src:
  - "'self'"
  - 'localhost'
  - 'assets-storage-statik-press.s3-eu-west-1.amazonaws.com'
connect-src:
  - "'self'"
